package com.business.creditmarketloanapi.service;

import com.business.creditmarketloanapi.dto.PaymentRequestDTO;
import com.business.creditmarketloanapi.dto.PaymentResponseDTO;
import com.business.creditmarketloanapi.entity.Loan;
import com.business.creditmarketloanapi.global.exceptions.AttributeException;
import com.business.creditmarketloanapi.global.exceptions.ResourceNotFoundException;

/**
 * Contains the API for payment request and consultation operations
 *
 * @author Julian Alvarado
 */
public interface PaymentService {
    /**
     * Makes a loan payment registration request
     *
     * @param paymentRequestDTO DTO object with the payment data
     * @return Returns the payment identifier, the loan identifier and the debt balance (DTO response object)
     * @throws ResourceNotFoundException Exception generated by the validation of the loan to which the payment is made
     * @throws AttributeException        Exception generated by the validation of the debt amount
     */
    public PaymentResponseDTO savePayment(PaymentRequestDTO paymentRequestDTO) throws ResourceNotFoundException, AttributeException;

    /**
     * Calculates the balance debt of a loan
     *
     * @param loan The loan to query
     * @return The amount of the debt
     */
    public Double getLoanDebt(Loan loan);
}
