-- Users app
INSERT INTO users (name, target) VALUES ('Alex Gomez','NEW');
INSERT INTO users (name, target) VALUES ('Carlos Lopez','NEW');
INSERT INTO users (name, target) VALUES ('Alvaro Ramos','NEW');
INSERT INTO users (name, target) VALUES ('Diego Castro','NEW');
INSERT INTO users (name, target) VALUES ('Jaime Velez','NEW');
INSERT INTO users (name, target) VALUES ('Patricia Martinez','NEW');
INSERT INTO users (name, target) VALUES ('Diana Acevedo','NEW');
INSERT INTO users (name, target) VALUES ('Mario Alvarez','NEW');
INSERT INTO users (name, target) VALUES ('Juan David Gonzalez','NEW');
INSERT INTO users (name, target) VALUES ('Alexander Ramos','NEW');
INSERT INTO users (name, target) VALUES ('Julian Gutierrez','FREQUENT');
INSERT INTO users (name, target) VALUES ('Edgar Torres','FREQUENT');
INSERT INTO users (name, target) VALUES ('Katherine Delgado','FREQUENT');
INSERT INTO users (name, target) VALUES ('Edward Segura','FREQUENT');
INSERT INTO users (name, target) VALUES ('Jhon Fredy Solis','FREQUENT');
INSERT INTO users (name, target) VALUES ('Pedro Perez','PREMIUM');
INSERT INTO users (name, target) VALUES ('Edwin Osorio','PREMIUM');
INSERT INTO users (name, target) VALUES ('Miguel Posada','PREMIUM');
INSERT INTO users (name, target) VALUES ('Jesus Sandoval','PREMIUM');
INSERT INTO users (name, target) VALUES ('Laura Gonzalez','PREMIUM');
-- Target parameters
INSERT INTO parameters (description, str_value) VALUES ('Min. loans number taken the last year in NEW target','0');
INSERT INTO parameters (description, str_value) VALUES ('Max. loans number taken the last year in NEW target','2');
INSERT INTO parameters (description, str_value) VALUES ('Min. loans volume taken last year in NEW target','0');
INSERT INTO parameters (description, str_value) VALUES ('Max. loans volume taken last year in NEW target','100000');
INSERT INTO parameters (description, str_value) VALUES ('NEW target rate','0.15');
INSERT INTO parameters (description, str_value) VALUES ('Maximum amount per loan in NEW target','500000');
INSERT INTO parameters (description, str_value) VALUES ('Min. loans number taken the last year in FREQUENT target','2');
INSERT INTO parameters (description, str_value) VALUES ('Max. loans number taken the last year in FREQUENT target','5');
INSERT INTO parameters (description, str_value) VALUES ('Min. loans volume taken last year in FREQUENT target','100000');
INSERT INTO parameters (description, str_value) VALUES ('Max. loans volume taken last year in FREQUENT target','500000');
INSERT INTO parameters (description, str_value) VALUES ('FREQUENT target rate','0.10');
INSERT INTO parameters (description, str_value) VALUES ('Maximum amount per loan in FREQUENT target','1000000');
INSERT INTO parameters (description, str_value) VALUES ('Min. loans number requested the last year in PREMIUM target','5');
INSERT INTO parameters (description, str_value) VALUES ('Max. loans number requested the last year in PREMIUM target','999999');
INSERT INTO parameters (description, str_value) VALUES ('Min. loans volume taken last year in PREMIUM target','500000');
INSERT INTO parameters (description, str_value) VALUES ('Max. loans volume taken last year in PREMIUM target','999999999999');
INSERT INTO parameters (description, str_value) VALUES ('PREMIUM target rate','0.05');
INSERT INTO parameters (description, str_value) VALUES ('Maximum amount per loan in PREMIUM target','5000000');