package com.business.creditmarketloanapi.global.exceptions;

import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.ResponseStatus;

/**
 * Represents the exception generated by not finding a model information record
 *
 * @author Julian Alvarado
 */
@ResponseStatus(HttpStatus.NOT_FOUND)
public class ResourceNotFoundException extends Exception {
    /**
     * Main exception constructor
     *
     * @param message The message generated or reported by the exception
     */
    public ResourceNotFoundException(String message) {
        super(message);
    }
}
