package com.business.creditmarketloanapi.controller;

import com.business.creditmarketloanapi.dto.PaymentRequestDTO;
import com.business.creditmarketloanapi.dto.ResponseDTO;
import com.business.creditmarketloanapi.global.exceptions.AttributeException;
import com.business.creditmarketloanapi.global.exceptions.ResourceNotFoundException;
import com.business.creditmarketloanapi.service.PaymentService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import javax.validation.Valid;

/**
 * Controller for requests related to payment operations
 *
 * @author Julian Alvarado
 */
@Validated
@RestController
@RequestMapping("/api/payment")
public class PaymentController {
    @Autowired
    private PaymentService paymentService;

    /**
     * Creates a loan payment
     *
     * @param paymentRequestDTO Body of the request with the data of the payment to register (request object DTO
     * @return HTTP response with status, payment ID, loan ID, and loan debt
     * @throws ResourceNotFoundException Exception generated by the validation of the loan to which the payment is made
     * @throws AttributeException        Exception generated by the validation of the debt amount
     */
    @PostMapping
    public ResponseEntity<ResponseDTO> createPayment(@Valid @RequestBody PaymentRequestDTO paymentRequestDTO) throws ResourceNotFoundException, AttributeException {
        return ResponseEntity.ok(new ResponseDTO(HttpStatus.OK, paymentService.savePayment(paymentRequestDTO)));
    }
}
